/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gym;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.util.Date;

/**
 *
 * @author ACER RYZEN 5
 */
public class BuyPackage extends javax.swing.JPanel implements database {
    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    
    String user, password;

    /**
     * Creates new form BuyPackage
     */
    public BuyPackage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        BuyBasic = new javax.swing.JPanel();
        BasicTitle = new javax.swing.JLabel();
        LamaSewa1 = new javax.swing.JLabel();
        Biaya1 = new javax.swing.JLabel();
        Bayar1 = new javax.swing.JLabel();
        CetakBuktiBasic = new javax.swing.JButton();
        LamaSewaBasic = new javax.swing.JComboBox<>();
        biayaBasic = new javax.swing.JScrollPane();
        biayabasic = new javax.swing.JTextPane();
        bayarbasic = new javax.swing.JTextField();
        Cancel1 = new javax.swing.JButton();
        BuyPremium = new javax.swing.JPanel();
        PremiumTitle = new javax.swing.JLabel();
        LamaSewa2 = new javax.swing.JLabel();
        Biaya2 = new javax.swing.JLabel();
        Bayar2 = new javax.swing.JLabel();
        CetakBuktiPremium = new javax.swing.JButton();
        LamaSewaPremium = new javax.swing.JComboBox<>();
        biayaPremium = new javax.swing.JScrollPane();
        biayapremium = new javax.swing.JTextPane();
        bayarpremium = new javax.swing.JTextField();
        Cancel2 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setMaximumSize(new java.awt.Dimension(492, 226));
        mainPanel.setMinimumSize(new java.awt.Dimension(492, 226));
        mainPanel.setPreferredSize(new java.awt.Dimension(492, 226));
        mainPanel.setLayout(new java.awt.CardLayout());

        BuyBasic.setBackground(new java.awt.Color(204, 204, 204));
        BuyBasic.setMinimumSize(new java.awt.Dimension(540, 370));

        BasicTitle.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BasicTitle.setText("LANGGANAN AKUN BASIC");

        LamaSewa1.setText("LAMA SEWA");

        Biaya1.setText("BIAYA");

        Bayar1.setText("BAYAR");

        CetakBuktiBasic.setText("OK");
        CetakBuktiBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakBuktiBasicActionPerformed(evt);
            }
        });

        LamaSewaBasic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 bulan", "4 bulan", "12 bulan" }));
        LamaSewaBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamaSewaBasicActionPerformed(evt);
            }
        });

        biayabasic.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                biayabasicAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        biayaBasic.setViewportView(biayabasic);

        bayarbasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarbasicActionPerformed(evt);
            }
        });

        Cancel1.setText("Cancel");
        Cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuyBasicLayout = new javax.swing.GroupLayout(BuyBasic);
        BuyBasic.setLayout(BuyBasicLayout);
        BuyBasicLayout.setHorizontalGroup(
            BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuyBasicLayout.createSequentialGroup()
                .addGroup(BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuyBasicLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(BasicTitle))
                    .addGroup(BuyBasicLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BuyBasicLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(CetakBuktiBasic, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BuyBasicLayout.createSequentialGroup()
                                .addGroup(BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LamaSewa1)
                                    .addComponent(Biaya1)
                                    .addComponent(Bayar1))
                                .addGap(48, 48, 48)
                                .addGroup(BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LamaSewaBasic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(biayaBasic)
                                    .addComponent(bayarbasic, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        BuyBasicLayout.setVerticalGroup(
            BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuyBasicLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(BasicTitle)
                .addGap(40, 40, 40)
                .addGroup(BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LamaSewa1)
                    .addComponent(LamaSewaBasic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Biaya1)
                    .addComponent(biayaBasic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bayar1)
                    .addComponent(bayarbasic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(BuyBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CetakBuktiBasic)
                    .addComponent(Cancel1))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        mainPanel.add(BuyBasic, "card8");

        BuyPremium.setBackground(new java.awt.Color(204, 204, 204));
        BuyPremium.setMinimumSize(new java.awt.Dimension(540, 370));

        PremiumTitle.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        PremiumTitle.setText("LANGGANAN AKUN PREMIUM");

        LamaSewa2.setText("LAMA SEWA");

        Biaya2.setText("BIAYA");

        Bayar2.setText("BAYAR");

        CetakBuktiPremium.setText("OK");
        CetakBuktiPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakBuktiPremiumActionPerformed(evt);
            }
        });

        LamaSewaPremium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 bulan", "4 bulan", "12 bulan" }));
        LamaSewaPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LamaSewaPremiumActionPerformed(evt);
            }
        });

        biayapremium.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                biayapremiumAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        biayaPremium.setViewportView(biayapremium);

        bayarpremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarpremiumActionPerformed(evt);
            }
        });

        Cancel2.setText("Cancel");
        Cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuyPremiumLayout = new javax.swing.GroupLayout(BuyPremium);
        BuyPremium.setLayout(BuyPremiumLayout);
        BuyPremiumLayout.setHorizontalGroup(
            BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuyPremiumLayout.createSequentialGroup()
                .addGroup(BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuyPremiumLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(PremiumTitle))
                    .addGroup(BuyPremiumLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BuyPremiumLayout.createSequentialGroup()
                                .addComponent(CetakBuktiPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BuyPremiumLayout.createSequentialGroup()
                                .addGroup(BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LamaSewa2)
                                    .addComponent(Biaya2)
                                    .addComponent(Bayar2))
                                .addGap(48, 48, 48)
                                .addGroup(BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LamaSewaPremium, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(biayaPremium)
                                    .addComponent(bayarpremium, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        BuyPremiumLayout.setVerticalGroup(
            BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuyPremiumLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(PremiumTitle)
                .addGap(40, 40, 40)
                .addGroup(BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LamaSewa2)
                    .addComponent(LamaSewaPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Biaya2)
                    .addComponent(biayaPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bayar2)
                    .addComponent(bayarpremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(BuyPremiumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CetakBuktiPremium)
                    .addComponent(Cancel2))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        mainPanel.add(BuyPremium, "card8");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        add(bodyPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void CetakBuktiBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakBuktiBasicActionPerformed
        // TODO add your handling code here:
        String SelectedValue = LamaSewaBasic.getSelectedItem().toString();
        
        int month;
        
        if (SelectedValue == "1 bulan"){
            month=1;
        }
        else if (SelectedValue == "4 bulan"){
            month=4;
        }
        else {
            month=12;
        }
        int biaya = Integer.parseInt(biayabasic.getText());
        int bayar = Integer.parseInt(bayarbasic.getText());
        int kembalian = bayar - biaya;
        buy ("Basic", biaya, kembalian, month);
    }//GEN-LAST:event_CetakBuktiBasicActionPerformed

    private void LamaSewaBasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamaSewaBasicActionPerformed
        // TODO add your handling code here:
        String SelectedValue = LamaSewaBasic.getSelectedItem().toString();

        if (SelectedValue == "1 bulan"){
            biayabasic.setText("80000");
        }
        else if (SelectedValue == "4 bulan"){
            biayabasic.setText("300000");
        }
        else {
            biayabasic.setText("900000");
        }
    }//GEN-LAST:event_LamaSewaBasicActionPerformed

    private void biayabasicAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_biayabasicAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_biayabasicAncestorAdded

    private void bayarbasicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarbasicActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bayarbasicActionPerformed

    private void CetakBuktiPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakBuktiPremiumActionPerformed
        // TODO add your handling code here:
        String SelectedValue = LamaSewaPremium.getSelectedItem().toString();
        
        int month;
        
        if (SelectedValue == "1 bulan"){
            month=1;
        }
        else if (SelectedValue == "4 bulan"){
            month=4;
        }
        else {
            month=12;
        }
        
        int biaya = Integer.parseInt(biayapremium.getText());
        int bayar = Integer.parseInt(bayarpremium.getText());
        int kembalian = bayar - biaya;
        buy ("Premium", biaya, kembalian, month);
    }//GEN-LAST:event_CetakBuktiPremiumActionPerformed

    private void LamaSewaPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LamaSewaPremiumActionPerformed
        // TODO add your handling code here:
        String SelectedValue = LamaSewaPremium.getSelectedItem().toString();

        if (SelectedValue == "1 bulan"){
            biayapremium.setText("100000");
        }
        else if (SelectedValue == "4 bulan"){
            biayapremium.setText("350000");
        }
        else {
            biayapremium.setText("1000000");
        }
    }//GEN-LAST:event_LamaSewaPremiumActionPerformed

    private void biayapremiumAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_biayapremiumAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_biayapremiumAncestorAdded

    private void bayarpremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarpremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarpremiumActionPerformed

    private void Cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel1ActionPerformed
        // TODO add your handling code here:
        kembali();
    }//GEN-LAST:event_Cancel1ActionPerformed

    private void Cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel2ActionPerformed
        // TODO add your handling code here:
        kembali();
    }//GEN-LAST:event_Cancel2ActionPerformed

    public JPanel getBuyBasic(){
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
            
        mainPanel.add(BuyBasic);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        return mainPanel;
    }
    
    public JPanel getBuyPremium(){
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(BuyPremium);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        return mainPanel;
    }
    
    public void kembali()
    {
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        Login logon = new Login();
        logon.setLoginInfo(user, password);
        
        mainPanel.add(logon.getMemberPanel());
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    int JumlahTransaksi, JumlahSkrg, TotalTransaksi, TotalSkrg;
    String nik;
    
    public void buy(String namaPaket, int hargaPaket, int kembalian, int month)
    {
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            
            String sqla = "SELECT * FROM Member WHERE Email='"+user+"' AND Password='"+password+"'";
            rs = stmt.executeQuery(sqla);
            
            while (rs.next()) {
                JumlahTransaksi = Integer.parseInt(rs.getString("JumlahTransaksi"));
                TotalTransaksi = Integer.parseInt(rs.getString("TotalTransaksi"));
                nik = rs.getString("NIK");
            }
            TotalSkrg = TotalTransaksi + hargaPaket;
            JumlahSkrg = JumlahTransaksi+1;
            
            Date d = new Date();
            
            int dateA, monthA, yearA;
            dateA = d.getDate();
            monthA = d.getMonth()+1;
            yearA = d.getYear()+1900;
            
            int dateB, monthB, yearB;
            dateB = dateA;
            monthB = monthA+month;
            if (monthB>=12){
                yearB=yearA+1;
                monthB=monthB-12;
            }
            else{
                yearB=yearA;
            }
            
            String datenow = monthA +"-"+dateA+"-"+yearA;
            String dateend = monthB +"-"+dateB+"-"+yearB;
            String sqlb = "INSERT INTO Transaksi (NIK, JenisTransaksi, Nominal, TanggalPembelian, TanggalSelesai) VALUES ('"+nik+"', '"+namaPaket+"', '"+hargaPaket+"', '"+datenow+"', '"+dateend+"')";
            stmt.execute(sqlb);
            String sql = "UPDATE Member SET StatusMember='"+namaPaket+"', JumlahTransaksi='"+JumlahSkrg+"', TotalTransaksi='"+TotalSkrg+"' WHERE Email='"+user+"' AND Password='"+password+"'";
            stmt.execute(sql);

            JOptionPane.showMessageDialog(null, "Pembelian Berhasil, \nKembalian Anda : Rp."+kembalian, "", JOptionPane.INFORMATION_MESSAGE);
            
            stmt.close();
            conn.close();
            
            kembali();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Pembelian Gagal", "", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void setLogin(String User, String Password)
    {
        user = User;
        password = Password;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BasicTitle;
    private javax.swing.JLabel Bayar1;
    private javax.swing.JLabel Bayar2;
    private javax.swing.JLabel Biaya1;
    private javax.swing.JLabel Biaya2;
    private javax.swing.JPanel BuyBasic;
    private javax.swing.JPanel BuyPremium;
    private javax.swing.JButton Cancel1;
    private javax.swing.JButton Cancel2;
    private javax.swing.JButton CetakBuktiBasic;
    private javax.swing.JButton CetakBuktiPremium;
    private javax.swing.JLabel LamaSewa1;
    private javax.swing.JLabel LamaSewa2;
    private javax.swing.JComboBox<String> LamaSewaBasic;
    private javax.swing.JComboBox<String> LamaSewaPremium;
    private javax.swing.JLabel PremiumTitle;
    private javax.swing.JTextField bayarbasic;
    private javax.swing.JTextField bayarpremium;
    private javax.swing.JScrollPane biayaBasic;
    private javax.swing.JScrollPane biayaPremium;
    private javax.swing.JTextPane biayabasic;
    private javax.swing.JTextPane biayapremium;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
