/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gym;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;

/**
 *
 * @author ACER RYZEN 5
 */
public class Daftar extends javax.swing.JPanel implements database {

    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;

    /**
     * Creates new form Daftar
     */
    public Daftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        DaftarPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Lnama = new javax.swing.JLabel();
        LJenisKelamin = new javax.swing.JLabel();
        Lemail = new javax.swing.JLabel();
        Lnik = new javax.swing.JLabel();
        LTanggalLahir = new javax.swing.JLabel();
        LnoHP = new javax.swing.JLabel();
        Lalamat = new javax.swing.JLabel();
        Tnama = new javax.swing.JTextField();
        Tnik = new javax.swing.JTextField();
        Temail = new javax.swing.JTextField();
        TnoHP = new javax.swing.JTextField();
        TanggalLahir = new javax.swing.JComboBox<>();
        BulanLahir = new javax.swing.JComboBox<>();
        TahunLahir = new javax.swing.JComboBox<>();
        TJenisKelamin = new javax.swing.JComboBox<>();
        Lkelurahan = new javax.swing.JLabel();
        Lkecamatan = new javax.swing.JLabel();
        Ljalan = new javax.swing.JLabel();
        Tjalan = new javax.swing.JTextField();
        Tkelurahan = new javax.swing.JTextField();
        Tkecamatan = new javax.swing.JTextField();
        Lkodepos = new javax.swing.JLabel();
        Tkodepos = new javax.swing.JTextField();
        Ltanggalmulai = new javax.swing.JLabel();
        TanggalMulai = new javax.swing.JComboBox<>();
        BulanMulai = new javax.swing.JComboBox<>();
        TahunMulai = new javax.swing.JComboBox<>();
        DAFTAR = new javax.swing.JToggleButton();
        Lno = new javax.swing.JLabel();
        Tno = new javax.swing.JTextField();
        Lrt = new javax.swing.JLabel();
        Trt = new javax.swing.JTextField();
        Lrw = new javax.swing.JLabel();
        Trw = new javax.swing.JTextField();
        Lpassword = new javax.swing.JLabel();
        Tpassword = new javax.swing.JPasswordField();
        InformasiDaftarPanel = new javax.swing.JPanel();
        InfoTitle = new javax.swing.JLabel();
        GoLogin = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        mainPanel.setLayout(new java.awt.CardLayout());

        DaftarPanel.setBackground(new java.awt.Color(204, 204, 204));
        DaftarPanel.setMinimumSize(new java.awt.Dimension(540, 370));

        Title.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        Title.setText("DAFTAR");

        Lnama.setText("Nama");

        LJenisKelamin.setText("Jenis kelamin");

        Lemail.setText("Email");

        Lnik.setText("NIK");

        LTanggalLahir.setText("Tanggal lahir");

        LnoHP.setText("Nomor HP");

        Lalamat.setText("Alamat");

        TanggalLahir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        TanggalLahir.setMaximumSize(new java.awt.Dimension(30, 22));
        TanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalLahirActionPerformed(evt);
            }
        });

        BulanLahir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        BulanLahir.setMaximumSize(new java.awt.Dimension(30, 22));
        BulanLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanLahirActionPerformed(evt);
            }
        });

        TahunLahir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        TahunLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunLahirActionPerformed(evt);
            }
        });

        TJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));

        Lkelurahan.setText("Kelurahan");

        Lkecamatan.setText("Kecamatan");

        Ljalan.setText("Jalan");

        Lkodepos.setText("Kode Pos");

        Ltanggalmulai.setText("Tanggal Bergabung");

        TanggalMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        TanggalMulai.setMaximumSize(new java.awt.Dimension(30, 22));
        TanggalMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalMulaiActionPerformed(evt);
            }
        });

        BulanMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        BulanMulai.setMaximumSize(new java.awt.Dimension(30, 22));
        BulanMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanMulaiActionPerformed(evt);
            }
        });

        TahunMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        TahunMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunMulaiActionPerformed(evt);
            }
        });

        DAFTAR.setText("DAFTAR");
        DAFTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAFTARActionPerformed(evt);
            }
        });

        Lno.setText("No");

        Lrt.setText("RT");

        Lrw.setText("RW");

        Lpassword.setText("Password");

        javax.swing.GroupLayout DaftarPanelLayout = new javax.swing.GroupLayout(DaftarPanel);
        DaftarPanel.setLayout(DaftarPanelLayout);
        DaftarPanelLayout.setHorizontalGroup(
            DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DaftarPanelLayout.createSequentialGroup()
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DaftarPanelLayout.createSequentialGroup()
                                .addComponent(Lnama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tnama))
                            .addGroup(DaftarPanelLayout.createSequentialGroup()
                                .addComponent(Lpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tpassword))
                            .addGroup(DaftarPanelLayout.createSequentialGroup()
                                .addComponent(Ltanggalmulai, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BulanMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TahunMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Title)
                            .addGroup(DaftarPanelLayout.createSequentialGroup()
                                .addComponent(LJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DaftarPanelLayout.createSequentialGroup()
                                .addComponent(LTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BulanLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TahunLahir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(DaftarPanelLayout.createSequentialGroup()
                                .addComponent(Lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Temail))
                            .addGroup(DaftarPanelLayout.createSequentialGroup()
                                .addComponent(Lnik, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tnik)))
                        .addGap(23, 23, 23)
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DaftarPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(DaftarPanelLayout.createSequentialGroup()
                                        .addComponent(Lkelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Tkelurahan))
                                    .addComponent(Lalamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DaftarPanelLayout.createSequentialGroup()
                                        .addComponent(Ljalan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Tjalan))
                                    .addGroup(DaftarPanelLayout.createSequentialGroup()
                                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Lkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Tkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Tkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(DaftarPanelLayout.createSequentialGroup()
                                        .addComponent(Lno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Tno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Lrt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Trt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lrw, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Trw, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(DaftarPanelLayout.createSequentialGroup()
                                .addComponent(LnoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TnoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(DaftarPanelLayout.createSequentialGroup()
                        .addComponent(DAFTAR)
                        .addGap(224, 224, 224)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        DaftarPanelLayout.setVerticalGroup(
            DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DaftarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnama)
                    .addComponent(Tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LnoHP)
                    .addComponent(TnoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DaftarPanelLayout.createSequentialGroup()
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tkelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkelurahan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkodepos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Trw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lrw)
                            .addComponent(Trt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lrt)
                            .addComponent(Tno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lno))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DaftarPanelLayout.createSequentialGroup()
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lnik)
                            .addComponent(Tnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lalamat))
                        .addGap(7, 7, 7)
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lemail)
                            .addComponent(Ljalan)
                            .addComponent(Tjalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lpassword)
                            .addComponent(Tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LTanggalLahir)
                            .addComponent(TanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BulanLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TahunLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkecamatan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LJenisKelamin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ltanggalmulai)
                            .addComponent(TanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BulanMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TahunMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addComponent(DAFTAR)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        mainPanel.add(DaftarPanel, "card7");

        InfoTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        InfoTitle.setText("Data Anda telah dimasukkan pada Database");

        GoLogin.setText("LOGIN");
        GoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InformasiDaftarPanelLayout = new javax.swing.GroupLayout(InformasiDaftarPanel);
        InformasiDaftarPanel.setLayout(InformasiDaftarPanelLayout);
        InformasiDaftarPanelLayout.setHorizontalGroup(
            InformasiDaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformasiDaftarPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(InformasiDaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoTitle)
                    .addGroup(InformasiDaftarPanelLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(GoLogin)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        InformasiDaftarPanelLayout.setVerticalGroup(
            InformasiDaftarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformasiDaftarPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(InfoTitle)
                .addGap(18, 18, 18)
                .addComponent(GoLogin)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        mainPanel.add(InformasiDaftarPanel, "card3");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, Short.MAX_VALUE)
        );

        add(bodyPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void TanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalLahirActionPerformed

    private void BulanLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanLahirActionPerformed

    private void TahunLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunLahirActionPerformed

    private void TanggalMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalMulaiActionPerformed

    private void BulanMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanMulaiActionPerformed

    private void TahunMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunMulaiActionPerformed

    private void DAFTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAFTARActionPerformed
        // TODO add your handling code here:
        try {
                Class.forName(JDBC_DRIVER);

                conn = DriverManager.getConnection(DB_URL, USER, PASS);
                stmt = conn.createStatement();

                String InsertMember = "INSERT INTO Member (Nama, NIK, TanggalLahir, JenisKelamin, AlamatLengkap, Email, Password, NomorHP, TanggalMulaiBergabung, StatusMember, JumlahTransaksi, TotalTransaksi) VALUES('"+Tnama.getText()+"', '"+Tnik.getText()+"', '"+BulanLahir.getSelectedItem()+"-"+TanggalLahir.getSelectedItem()+"-"+TahunLahir.getSelectedItem()+"', '"+TJenisKelamin.getSelectedItem()+"', '"+Tjalan.getText()+", "+Tkelurahan.getText()+", "+Tkecamatan.getText()+", RT "+Trt.getText()+", RW "+Trw.getText()+", No "+Tno.getText()+" "+Tkodepos.getText()+"', '"+Temail.getText()+"', '"+Tpassword.getText()+"', '"+TnoHP.getText()+"', '"+BulanMulai.getSelectedItem()+"-"+TanggalMulai.getSelectedItem()+"-"+TahunMulai.getSelectedItem()+"', 'Belum Berlangganan', '0', '0')";
                stmt.execute(InsertMember);

                String InsertAlamatMember = "INSERT INTO AlamatMember (NIK, Jalan, RT, RW, Nomor, Kelurahan, Kecamatan, KodePos) VALUES('"+Tnik.getText()+"', '"+Tjalan.getText()+"', '"+Trt.getText()+"', '"+Trw.getText()+"', '"+Tno.getText()+"', '"+Tkelurahan.getText()+"', '"+Tkecamatan.getText()+"', '"+Tkodepos.getText()+"')";
                stmt.execute(InsertAlamatMember);

                JOptionPane.showMessageDialog(null, "Daftar Berhasil Dilakukan", "", JOptionPane.INFORMATION_MESSAGE);

                stmt.close();
                conn.close();
                
                mainPanel.removeAll();
                mainPanel.repaint();
                mainPanel.revalidate();

                mainPanel.add(InformasiDaftarPanel);
                mainPanel.repaint();
                mainPanel.revalidate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Daftar Gagal Dilakukan", "", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_DAFTARActionPerformed

    private void GoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoLoginActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        Login masuk = new Login();

        mainPanel.add(masuk.getLoginPanel());
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_GoLoginActionPerformed

    public JPanel getMainPanel(){
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(DaftarPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        return mainPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BulanLahir;
    private javax.swing.JComboBox<String> BulanMulai;
    private javax.swing.JToggleButton DAFTAR;
    private javax.swing.JPanel DaftarPanel;
    private javax.swing.JButton GoLogin;
    private javax.swing.JLabel InfoTitle;
    private javax.swing.JPanel InformasiDaftarPanel;
    private javax.swing.JLabel LJenisKelamin;
    private javax.swing.JLabel LTanggalLahir;
    private javax.swing.JLabel Lalamat;
    private javax.swing.JLabel Lemail;
    private javax.swing.JLabel Ljalan;
    private javax.swing.JLabel Lkecamatan;
    private javax.swing.JLabel Lkelurahan;
    private javax.swing.JLabel Lkodepos;
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel Lnik;
    private javax.swing.JLabel Lno;
    private javax.swing.JLabel LnoHP;
    private javax.swing.JLabel Lpassword;
    private javax.swing.JLabel Lrt;
    private javax.swing.JLabel Lrw;
    private javax.swing.JLabel Ltanggalmulai;
    private javax.swing.JComboBox<String> TJenisKelamin;
    private javax.swing.JComboBox<String> TahunLahir;
    private javax.swing.JComboBox<String> TahunMulai;
    private javax.swing.JComboBox<String> TanggalLahir;
    private javax.swing.JComboBox<String> TanggalMulai;
    private javax.swing.JTextField Temail;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField Tjalan;
    private javax.swing.JTextField Tkecamatan;
    private javax.swing.JTextField Tkelurahan;
    private javax.swing.JTextField Tkodepos;
    private javax.swing.JTextField Tnama;
    private javax.swing.JTextField Tnik;
    private javax.swing.JTextField Tno;
    private javax.swing.JTextField TnoHP;
    private javax.swing.JPasswordField Tpassword;
    private javax.swing.JTextField Trt;
    private javax.swing.JTextField Trw;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
