/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gym;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER RYZEN 5
 */
public class KelolaPekerja extends javax.swing.JPanel implements database {

    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    
    /**
     * Creates new form KelolaPekerja
     */
    public KelolaPekerja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        KelolaPekerja = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        Add = new javax.swing.JPanel();
        AddTitle = new javax.swing.JLabel();
        Lnama = new javax.swing.JLabel();
        LJenisKelamin = new javax.swing.JLabel();
        Lemail = new javax.swing.JLabel();
        Lnik = new javax.swing.JLabel();
        LTanggalLahir = new javax.swing.JLabel();
        LnoHP = new javax.swing.JLabel();
        Lalamat = new javax.swing.JLabel();
        Lstatus = new javax.swing.JLabel();
        Tnama = new javax.swing.JTextField();
        Tnik = new javax.swing.JTextField();
        Temail = new javax.swing.JTextField();
        TnoHP = new javax.swing.JTextField();
        TanggalLahir = new javax.swing.JComboBox<>();
        BulanLahir = new javax.swing.JComboBox<>();
        TahunLahir = new javax.swing.JComboBox<>();
        TJenisKelamin = new javax.swing.JComboBox<>();
        Lkelurahan = new javax.swing.JLabel();
        Lkecamatan = new javax.swing.JLabel();
        Ljalan = new javax.swing.JLabel();
        Tjalan = new javax.swing.JTextField();
        Tkelurahan = new javax.swing.JTextField();
        Tkecamatan = new javax.swing.JTextField();
        TStatus = new javax.swing.JComboBox<>();
        Lkodepos = new javax.swing.JLabel();
        Tkodepos = new javax.swing.JTextField();
        Ltanggalmulai = new javax.swing.JLabel();
        TanggalMulai = new javax.swing.JComboBox<>();
        BulanMulai = new javax.swing.JComboBox<>();
        TahunMulai = new javax.swing.JComboBox<>();
        SIMPAN = new javax.swing.JToggleButton();
        Lno = new javax.swing.JLabel();
        Tno = new javax.swing.JTextField();
        Lrt = new javax.swing.JLabel();
        Trt = new javax.swing.JTextField();
        Lrw = new javax.swing.JLabel();
        Trw = new javax.swing.JTextField();
        Ljabatan = new javax.swing.JLabel();
        Tjabatan = new javax.swing.JTextField();
        K1 = new javax.swing.JToggleButton();
        Read = new javax.swing.JPanel();
        TablePekerja = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        K2 = new javax.swing.JToggleButton();
        Edit = new javax.swing.JPanel();
        TablePekerja1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        LNo = new javax.swing.JLabel();
        TNo = new javax.swing.JTextField();
        btnOK = new javax.swing.JToggleButton();
        K3 = new javax.swing.JToggleButton();
        Update = new javax.swing.JPanel();
        AddTitle1 = new javax.swing.JLabel();
        Lnama1 = new javax.swing.JLabel();
        LJenisKelamin1 = new javax.swing.JLabel();
        Lemail1 = new javax.swing.JLabel();
        Lnik1 = new javax.swing.JLabel();
        LTanggalLahir1 = new javax.swing.JLabel();
        LnoHP1 = new javax.swing.JLabel();
        Lalamat1 = new javax.swing.JLabel();
        Lstatus1 = new javax.swing.JLabel();
        Tnama1 = new javax.swing.JTextField();
        Tnik1 = new javax.swing.JTextField();
        Temail1 = new javax.swing.JTextField();
        TnoHP1 = new javax.swing.JTextField();
        TanggalLahir1 = new javax.swing.JComboBox<>();
        BulanLahir1 = new javax.swing.JComboBox<>();
        TahunLahir1 = new javax.swing.JComboBox<>();
        TJenisKelamin1 = new javax.swing.JComboBox<>();
        Lkelurahan1 = new javax.swing.JLabel();
        Lkecamatan1 = new javax.swing.JLabel();
        Ljalan1 = new javax.swing.JLabel();
        Tjalan1 = new javax.swing.JTextField();
        Tkelurahan1 = new javax.swing.JTextField();
        Tkecamatan1 = new javax.swing.JTextField();
        TStatus1 = new javax.swing.JComboBox<>();
        Lkodepos1 = new javax.swing.JLabel();
        Tkodepos1 = new javax.swing.JTextField();
        Ltanggalmulai1 = new javax.swing.JLabel();
        TanggalMulai1 = new javax.swing.JComboBox<>();
        BulanMulai1 = new javax.swing.JComboBox<>();
        TahunMulai1 = new javax.swing.JComboBox<>();
        SIMPAN1 = new javax.swing.JToggleButton();
        Lno1 = new javax.swing.JLabel();
        Tno1 = new javax.swing.JTextField();
        Lrt1 = new javax.swing.JLabel();
        Trt1 = new javax.swing.JTextField();
        Lrw1 = new javax.swing.JLabel();
        Trw1 = new javax.swing.JTextField();
        Ljabatan1 = new javax.swing.JLabel();
        Tjabatan1 = new javax.swing.JTextField();
        K4 = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(684, 316));
        setLayout(new java.awt.CardLayout());

        bodyPanel.setMaximumSize(new java.awt.Dimension(717, 316));
        bodyPanel.setMinimumSize(new java.awt.Dimension(717, 316));
        bodyPanel.setPreferredSize(new java.awt.Dimension(717, 316));

        mainPanel.setMaximumSize(new java.awt.Dimension(600, 400));
        mainPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        mainPanel.setLayout(new java.awt.CardLayout());

        KelolaPekerja.setBackground(new java.awt.Color(204, 204, 204));
        KelolaPekerja.setMinimumSize(new java.awt.Dimension(540, 370));

        Title.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Title.setText("KELOLA PEKERJA");

        btnTambah.setText("TAMBAH PEKERJA");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE PEKERJA");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRead.setText("LIHAT DATA PEKERJA");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KelolaPekerjaLayout = new javax.swing.GroupLayout(KelolaPekerja);
        KelolaPekerja.setLayout(KelolaPekerjaLayout);
        KelolaPekerjaLayout.setHorizontalGroup(
            KelolaPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelolaPekerjaLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(KelolaPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelolaPekerjaLayout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(111, 111, 111)))
                .addGap(111, 111, 111))
        );
        KelolaPekerjaLayout.setVerticalGroup(
            KelolaPekerjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelolaPekerjaLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(Title)
                .addGap(36, 36, 36)
                .addComponent(btnTambah)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnRead)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        mainPanel.add(KelolaPekerja, "card7");

        Add.setBackground(new java.awt.Color(204, 204, 204));
        Add.setMinimumSize(new java.awt.Dimension(540, 370));

        AddTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        AddTitle.setText("Tambahkan Data Pekerja");

        Lnama.setText("Nama");

        LJenisKelamin.setText("Jenis kelamin");

        Lemail.setText("Email");

        Lnik.setText("NIK");

        LTanggalLahir.setText("Tanggal lahir");

        LnoHP.setText("Nomor HP");

        Lalamat.setText("Alamat");

        Lstatus.setText("Status Pekerja");

        TanggalLahir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        TanggalLahir.setMaximumSize(new java.awt.Dimension(30, 22));
        TanggalLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalLahirActionPerformed(evt);
            }
        });

        BulanLahir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        BulanLahir.setMaximumSize(new java.awt.Dimension(30, 22));
        BulanLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanLahirActionPerformed(evt);
            }
        });

        TahunLahir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        TahunLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunLahirActionPerformed(evt);
            }
        });

        TJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));

        Lkelurahan.setText("Kelurahan");

        Lkecamatan.setText("Kecamatan");

        Ljalan.setText("Jalan");

        TStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Cuti", "Tidak Aktif" }));

        Lkodepos.setText("Kode Pos");

        Ltanggalmulai.setText("Tanggal Mulai");

        TanggalMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        TanggalMulai.setMaximumSize(new java.awt.Dimension(30, 22));
        TanggalMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalMulaiActionPerformed(evt);
            }
        });

        BulanMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        BulanMulai.setMaximumSize(new java.awt.Dimension(30, 22));
        BulanMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanMulaiActionPerformed(evt);
            }
        });

        TahunMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        TahunMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunMulaiActionPerformed(evt);
            }
        });

        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        Lno.setText("No");

        Lrt.setText("RT");

        Lrw.setText("RW");

        Ljabatan.setText("Jabatan");

        K1.setText("KEMBALI");
        K1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddLayout = new javax.swing.GroupLayout(Add);
        Add.setLayout(AddLayout);
        AddLayout.setHorizontalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addComponent(Lnama, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(AddLayout.createSequentialGroup()
                                .addComponent(Lkelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tkelurahan))
                            .addComponent(Lalamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddLayout.createSequentialGroup()
                                .addComponent(Ljabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddLayout.createSequentialGroup()
                                .addComponent(Ljalan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tjalan))
                            .addGroup(AddLayout.createSequentialGroup()
                                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AddLayout.createSequentialGroup()
                                .addComponent(Lno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Tno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lrt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Trt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lrw, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Trw, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(AddLayout.createSequentialGroup()
                                    .addComponent(Ltanggalmulai, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BulanMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TahunMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(AddTitle)
                                .addGroup(AddLayout.createSequentialGroup()
                                    .addComponent(Lstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(AddLayout.createSequentialGroup()
                                    .addComponent(LJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLayout.createSequentialGroup()
                                    .addComponent(LTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(BulanLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TahunLahir, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(AddLayout.createSequentialGroup()
                                    .addComponent(LnoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TnoHP))
                                .addGroup(AddLayout.createSequentialGroup()
                                    .addComponent(Lemail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Temail))
                                .addGroup(AddLayout.createSequentialGroup()
                                    .addComponent(Lnik, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Tnik)))
                            .addGroup(AddLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(SIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(K1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        AddLayout.setVerticalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnama)
                    .addComponent(Tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ljabatan)
                    .addComponent(Tjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLayout.createSequentialGroup()
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tkelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkelurahan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Tkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkodepos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Trw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lrw)
                            .addComponent(Trt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lrt)
                            .addComponent(Tno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lno))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLayout.createSequentialGroup()
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lnik)
                            .addComponent(Tnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lalamat))
                        .addGap(7, 7, 7)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lemail)
                            .addComponent(Ljalan)
                            .addComponent(Tjalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LnoHP)
                            .addComponent(TnoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LTanggalLahir)
                            .addComponent(TanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BulanLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TahunLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkecamatan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LJenisKelamin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ltanggalmulai)
                            .addComponent(TanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BulanMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TahunMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SIMPAN)
                    .addComponent(K1))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        mainPanel.add(Add, "card7");

        Read.setBackground(new java.awt.Color(204, 204, 204));
        Read.setMinimumSize(new java.awt.Dimension(540, 370));

        DefaultTableModel model = new DefaultTableModel();
        String[] columnNames={"No", "Nama", "NIK", "Tanggal Lahir", "Jenis Kelamin", "Alamat Lengkap", "Jabatan",
            "Email", "Nomor HP", "Tanggal Mulai Bekerja", "Status"};
        model.setColumnIdentifiers(columnNames);
        jTable1.setModel(model);
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            String sql = "SELECT * FROM Pekerja ORDER BY NoPekerja ASC";
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("NoPekerja"), rs.getString("Nama"), rs.getString("NIK"),rs.getString("TanggalLahir"),rs.getString("JenisKelamin"),rs.getString("AlamatLengkap"),
                    rs.getString("Jabatan"), rs.getString("Email"), rs.getString("NomorHP"), rs.getString("TanggalMulaiBekerja"), rs.getString("Status")});
        }

        stmt.close();
        conn.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Pengambilan Data Gagal", "", JOptionPane.ERROR_MESSAGE);
    }
    TablePekerja.setViewportView(jTable1);

    K2.setText("KEMBALI");
    K2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            K2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout ReadLayout = new javax.swing.GroupLayout(Read);
    Read.setLayout(ReadLayout);
    ReadLayout.setHorizontalGroup(
        ReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ReadLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(TablePekerja, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(ReadLayout.createSequentialGroup()
            .addGap(260, 260, 260)
            .addComponent(K2)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    ReadLayout.setVerticalGroup(
        ReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ReadLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(TablePekerja, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addComponent(K2)
            .addContainerGap())
    );

    mainPanel.add(Read, "card7");

    Edit.setBackground(new java.awt.Color(204, 204, 204));
    Edit.setMinimumSize(new java.awt.Dimension(540, 370));

    DefaultTableModel model1 = new DefaultTableModel();
    String[] columnNames1={"No", "Nama", "NIK", "Tanggal Lahir", "Jenis Kelamin", "Alamat Lengkap", "Jabatan",
        "Email", "Nomor HP", "Tanggal Mulai Bekerja", "Status"};
    model1.setColumnIdentifiers(columnNames1);
    jTable2.setModel(model1);
    try {
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        stmt = conn.createStatement();
        String sql = "SELECT * FROM Pekerja ORDER BY NoPekerja ASC";
        rs = stmt.executeQuery(sql);

        while (rs.next()) {
            model1.addRow(new Object[]{rs.getString("NoPekerja"), rs.getString("Nama"), rs.getString("NIK"),rs.getString("TanggalLahir"),rs.getString("JenisKelamin"),rs.getString("AlamatLengkap"),
                rs.getString("Jabatan"), rs.getString("Email"), rs.getString("NomorHP"), rs.getString("TanggalMulaiBekerja"), rs.getString("Status")});
    }

    stmt.close();
    conn.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Pengambilan Data Gagal", "", JOptionPane.ERROR_MESSAGE);
    }
    TablePekerja1.setViewportView(jTable2);

    LNo.setText("Masukkan Nomor yang Ingin  Diedit");

    TNo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TNoActionPerformed(evt);
        }
    });

    btnOK.setText("OK");
    btnOK.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnOKActionPerformed(evt);
        }
    });

    K3.setText("KEMBALI");
    K3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            K3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout EditLayout = new javax.swing.GroupLayout(Edit);
    Edit.setLayout(EditLayout);
    EditLayout.setHorizontalGroup(
        EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(EditLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TablePekerja1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addGroup(EditLayout.createSequentialGroup()
                    .addComponent(LNo)
                    .addGap(18, 18, 18)
                    .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EditLayout.createSequentialGroup()
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(K3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    EditLayout.setVerticalGroup(
        EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditLayout.createSequentialGroup()
            .addContainerGap(84, Short.MAX_VALUE)
            .addComponent(TablePekerja1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(23, 23, 23)
            .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(LNo)
                .addComponent(TNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(61, 61, 61)
            .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnOK)
                .addComponent(K3))
            .addGap(36, 36, 36))
    );

    mainPanel.add(Edit, "card7");

    Update.setBackground(new java.awt.Color(204, 204, 204));
    Update.setMinimumSize(new java.awt.Dimension(540, 370));

    AddTitle1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
    AddTitle1.setText("Tambahkan Data Pekerja");

    Lnama1.setText("Nama");

    LJenisKelamin1.setText("Jenis kelamin");

    Lemail1.setText("Email");

    Lnik1.setText("NIK");

    LTanggalLahir1.setText("Tanggal lahir");

    LnoHP1.setText("Nomor HP");

    Lalamat1.setText("Alamat");

    Lstatus1.setText("Status Pekerja");

    TanggalLahir1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
    TanggalLahir1.setMaximumSize(new java.awt.Dimension(30, 22));
    TanggalLahir1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TanggalLahir1ActionPerformed(evt);
        }
    });

    BulanLahir1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
    BulanLahir1.setMaximumSize(new java.awt.Dimension(30, 22));
    BulanLahir1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BulanLahir1ActionPerformed(evt);
        }
    });

    TahunLahir1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
    TahunLahir1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TahunLahir1ActionPerformed(evt);
        }
    });

    TJenisKelamin1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));

    Lkelurahan1.setText("Kelurahan");

    Lkecamatan1.setText("Kecamatan");

    Ljalan1.setText("Jalan");

    TStatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Cuti", "Tidak Aktif" }));

    Lkodepos1.setText("Kode Pos");

    Ltanggalmulai1.setText("Tanggal Mulai");

    TanggalMulai1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
    TanggalMulai1.setMaximumSize(new java.awt.Dimension(30, 22));
    TanggalMulai1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TanggalMulai1ActionPerformed(evt);
        }
    });

    BulanMulai1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
    BulanMulai1.setMaximumSize(new java.awt.Dimension(30, 22));
    BulanMulai1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BulanMulai1ActionPerformed(evt);
        }
    });

    TahunMulai1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
    TahunMulai1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TahunMulai1ActionPerformed(evt);
        }
    });

    SIMPAN1.setText("SIMPAN");
    SIMPAN1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            SIMPAN1ActionPerformed(evt);
        }
    });

    Lno1.setText("No");

    Lrt1.setText("RT");

    Lrw1.setText("RW");

    Ljabatan1.setText("Jabatan");

    K4.setText("KEMBALI");
    K4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            K4ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout UpdateLayout = new javax.swing.GroupLayout(Update);
    Update.setLayout(UpdateLayout);
    UpdateLayout.setHorizontalGroup(
        UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(UpdateLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(UpdateLayout.createSequentialGroup()
                    .addComponent(Lnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Tnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(UpdateLayout.createSequentialGroup()
                            .addComponent(Lkelurahan1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Tkelurahan1))
                        .addComponent(Lalamat1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdateLayout.createSequentialGroup()
                            .addComponent(Ljabatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Tjabatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdateLayout.createSequentialGroup()
                            .addComponent(Ljalan1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Tjalan1))
                        .addGroup(UpdateLayout.createSequentialGroup()
                            .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Lkecamatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lkodepos1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Tkecamatan1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tkodepos1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(UpdateLayout.createSequentialGroup()
                            .addComponent(Lno1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Tno1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Lrt1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Trt1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Lrw1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Trw1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(UpdateLayout.createSequentialGroup()
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(UpdateLayout.createSequentialGroup()
                                .addComponent(Ltanggalmulai1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TanggalMulai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BulanMulai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TahunMulai1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AddTitle1)
                            .addGroup(UpdateLayout.createSequentialGroup()
                                .addComponent(Lstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TStatus1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(UpdateLayout.createSequentialGroup()
                                .addComponent(LJenisKelamin1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TJenisKelamin1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateLayout.createSequentialGroup()
                                .addComponent(LTanggalLahir1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TanggalLahir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BulanLahir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TahunLahir1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(UpdateLayout.createSequentialGroup()
                                .addComponent(LnoHP1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TnoHP1))
                            .addGroup(UpdateLayout.createSequentialGroup()
                                .addComponent(Lemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Temail1))
                            .addGroup(UpdateLayout.createSequentialGroup()
                                .addComponent(Lnik1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tnik1)))
                        .addGroup(UpdateLayout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(SIMPAN1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addComponent(K4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(58, Short.MAX_VALUE))
    );
    UpdateLayout.setVerticalGroup(
        UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(UpdateLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(AddTitle1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Lnama1)
                .addComponent(Tnama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Ljabatan1)
                .addComponent(Tjabatan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateLayout.createSequentialGroup()
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tkelurahan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lkelurahan1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Tkecamatan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tkodepos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lkodepos1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Trw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lrw1)
                        .addComponent(Trt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lrt1)
                        .addComponent(Tno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lno1))
                    .addGap(25, 25, 25))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateLayout.createSequentialGroup()
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lnik1)
                        .addComponent(Tnik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lalamat1))
                    .addGap(7, 7, 7)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Temail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lemail1)
                        .addComponent(Ljalan1)
                        .addComponent(Tjalan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LnoHP1)
                        .addComponent(TnoHP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LTanggalLahir1)
                        .addComponent(TanggalLahir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BulanLahir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TahunLahir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Lkecamatan1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TJenisKelamin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LJenisKelamin1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ltanggalmulai1)
                        .addComponent(TanggalMulai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BulanMulai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TahunMulai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Lstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SIMPAN1)
                .addComponent(K4))
            .addContainerGap(113, Short.MAX_VALUE))
    );

    mainPanel.add(Update, "card7");

    javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
    bodyPanel.setLayout(bodyPanelLayout);
    bodyPanelLayout.setHorizontalGroup(
        bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bodyPanelLayout.createSequentialGroup()
            .addGap(648, 648, 648)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    bodyPanelLayout.setVerticalGroup(
        bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    add(bodyPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(Add);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void TahunMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunMulaiActionPerformed

    private void BulanMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanMulaiActionPerformed

    private void TanggalMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalMulaiActionPerformed

    private void TahunLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunLahirActionPerformed

    private void BulanLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanLahirActionPerformed

    private void TanggalLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalLahirActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(Edit);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(Read);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnReadActionPerformed

    private void TNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        Login admin = new Login();

        mainPanel.add(admin.getAdminPanel());
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnBackActionPerformed

    private void K1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K1ActionPerformed
        // TODO add your handling code here:
        kembali();
    }//GEN-LAST:event_K1ActionPerformed

    private void K2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K2ActionPerformed
        // TODO add your handling code here:
        kembali();
    }//GEN-LAST:event_K2ActionPerformed

    private void K3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K3ActionPerformed
        // TODO add your handling code here:
        kembali();
    }//GEN-LAST:event_K3ActionPerformed

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
        Add();
        kembali();
    }//GEN-LAST:event_SIMPANActionPerformed

    private void TanggalLahir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalLahir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalLahir1ActionPerformed

    private void BulanLahir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanLahir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanLahir1ActionPerformed

    private void TahunLahir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunLahir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunLahir1ActionPerformed

    private void TanggalMulai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalMulai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalMulai1ActionPerformed

    private void BulanMulai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanMulai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanMulai1ActionPerformed

    private void TahunMulai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunMulai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunMulai1ActionPerformed

    private void SIMPAN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPAN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SIMPAN1ActionPerformed

    private void K4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K4ActionPerformed
        // TODO add your handling code here:
        Add(pilih);
        kembali();
    }//GEN-LAST:event_K4ActionPerformed
    int pilih;
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        pilih = Integer.parseInt(TNo.getText());
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(Update);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnOKActionPerformed

    public JPanel getKelolaPekerja(){
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(KelolaPekerja);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        return mainPanel;
    }
    
    public void kembali()
    {
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(KelolaPekerja);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    public void Add(){
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            
            String Pekerja = "INSERT INTO Pekerja (Nama, NIK, TanggalLahir, JenisKelamin, AlamatLengkap, Jabatan, Email, NomorHP, TanggalMulaiBekerja, Status) VALUES('"+Tnama.getText()+"', '"+Tnik.getText()+"', '"+BulanLahir.getSelectedItem()+"-"+TanggalLahir.getSelectedItem()+"-"+TahunLahir.getSelectedItem()+"', '"+TJenisKelamin.getSelectedItem()+"', '"+Tjalan.getText()+", "+Tkelurahan.getText()+", "+Tkecamatan.getText()+", RT "+Trt.getText()+", RW "+Trw.getText()+", No "+Tno.getText()+" "+Tkodepos.getText()+"', '"+Tjabatan.getText()+"', '"+Temail.getText()+"', '"+TnoHP.getText()+"', '"+BulanMulai.getSelectedItem()+"-"+TanggalMulai.getSelectedItem()+"-"+TahunMulai.getSelectedItem()+"', '"+TStatus.getSelectedItem()+"')";
            stmt.execute(Pekerja);
            
            String InsertAlamatPekerja = "INSERT INTO AlamatPekerja (NIK, Jalan, RT, RW, Nomor, Kelurahan, Kecamatan, KodePos) VALUES('"+Tnik.getText()+"', '"+Tjalan.getText()+"', '"+Trt.getText()+"', '"+Trw.getText()+"', '"+Tno.getText()+"', '"+Tkelurahan.getText()+"', '"+Tkecamatan.getText()+"', '"+Tkodepos.getText()+"')";
            stmt.execute(InsertAlamatPekerja);
            
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil", "", JOptionPane.INFORMATION_MESSAGE);

            stmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Gagal", "", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void Add(int pilihan){
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            
            
            
            String AlamatPekerja = "DROP FROM AlamatPekerja WHERE NoPekerja='"+pilih+"'";
            stmt.execute(AlamatPekerja);
            
            String Pekerja = "UPDATE Pekerja SET Nama='"+Tnama1.getText()+"', NIK='"+Tnik1.getText()+"', TanggalLahir='"+BulanLahir1.getSelectedItem()+"-"+TanggalLahir1.getSelectedItem()+"-"+TahunLahir1.getSelectedItem()+"', JenisKelamin='"+TJenisKelamin1.getSelectedItem()+"', AlamatLengkap='"+Tjalan1.getText()+", "+Tkelurahan1.getText()+", "+Tkecamatan1.getText()+", RT "+Trt1.getText()+", RW "+Trw1.getText()+", No "+Tno1.getText()+" "+Tkodepos1.getText()+"', Jabatan='"+Tjabatan1.getText()+"', Email='"+Temail1.getText()+"', NomorHP='"+TnoHP1.getText()+"', TanggalMulaiBekerja='"+BulanMulai1.getSelectedItem()+"-"+TanggalMulai1.getSelectedItem()+"-"+TahunMulai1.getSelectedItem()+"', Status='"+TStatus1.getSelectedItem()+"' WHERE NoPekerja='"+pilih+"'";
            stmt.execute(Pekerja);
            
            String InsertAlamatPekerja = "INSERT INTO AlamatPekerja (NIK, Jalan, RT, RW, Nomor, Kelurahan, Kecamatan, KodePos) VALUES('"+Tnik.getText()+"', '"+Tjalan.getText()+"', '"+Trt.getText()+"', '"+Trw.getText()+"', '"+Tno.getText()+"', '"+Tkelurahan.getText()+"', '"+Tkecamatan.getText()+"', '"+Tkodepos.getText()+"')";
            stmt.execute(InsertAlamatPekerja);
            
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil", "", JOptionPane.INFORMATION_MESSAGE);

            stmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Gagal", "", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add;
    private javax.swing.JLabel AddTitle;
    private javax.swing.JLabel AddTitle1;
    private javax.swing.JComboBox<String> BulanLahir;
    private javax.swing.JComboBox<String> BulanLahir1;
    private javax.swing.JComboBox<String> BulanMulai;
    private javax.swing.JComboBox<String> BulanMulai1;
    private javax.swing.JPanel Edit;
    private javax.swing.JToggleButton K1;
    private javax.swing.JToggleButton K2;
    private javax.swing.JToggleButton K3;
    private javax.swing.JToggleButton K4;
    private javax.swing.JPanel KelolaPekerja;
    private javax.swing.JLabel LJenisKelamin;
    private javax.swing.JLabel LJenisKelamin1;
    private javax.swing.JLabel LNo;
    private javax.swing.JLabel LTanggalLahir;
    private javax.swing.JLabel LTanggalLahir1;
    private javax.swing.JLabel Lalamat;
    private javax.swing.JLabel Lalamat1;
    private javax.swing.JLabel Lemail;
    private javax.swing.JLabel Lemail1;
    private javax.swing.JLabel Ljabatan;
    private javax.swing.JLabel Ljabatan1;
    private javax.swing.JLabel Ljalan;
    private javax.swing.JLabel Ljalan1;
    private javax.swing.JLabel Lkecamatan;
    private javax.swing.JLabel Lkecamatan1;
    private javax.swing.JLabel Lkelurahan;
    private javax.swing.JLabel Lkelurahan1;
    private javax.swing.JLabel Lkodepos;
    private javax.swing.JLabel Lkodepos1;
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel Lnama1;
    private javax.swing.JLabel Lnik;
    private javax.swing.JLabel Lnik1;
    private javax.swing.JLabel Lno;
    private javax.swing.JLabel Lno1;
    private javax.swing.JLabel LnoHP;
    private javax.swing.JLabel LnoHP1;
    private javax.swing.JLabel Lrt;
    private javax.swing.JLabel Lrt1;
    private javax.swing.JLabel Lrw;
    private javax.swing.JLabel Lrw1;
    private javax.swing.JLabel Lstatus;
    private javax.swing.JLabel Lstatus1;
    private javax.swing.JLabel Ltanggalmulai;
    private javax.swing.JLabel Ltanggalmulai1;
    private javax.swing.JPanel Read;
    private javax.swing.JToggleButton SIMPAN;
    private javax.swing.JToggleButton SIMPAN1;
    private javax.swing.JComboBox<String> TJenisKelamin;
    private javax.swing.JComboBox<String> TJenisKelamin1;
    private javax.swing.JTextField TNo;
    private javax.swing.JComboBox<String> TStatus;
    private javax.swing.JComboBox<String> TStatus1;
    private javax.swing.JScrollPane TablePekerja;
    private javax.swing.JScrollPane TablePekerja1;
    private javax.swing.JComboBox<String> TahunLahir;
    private javax.swing.JComboBox<String> TahunLahir1;
    private javax.swing.JComboBox<String> TahunMulai;
    private javax.swing.JComboBox<String> TahunMulai1;
    private javax.swing.JComboBox<String> TanggalLahir;
    private javax.swing.JComboBox<String> TanggalLahir1;
    private javax.swing.JComboBox<String> TanggalMulai;
    private javax.swing.JComboBox<String> TanggalMulai1;
    private javax.swing.JTextField Temail;
    private javax.swing.JTextField Temail1;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField Tjabatan;
    private javax.swing.JTextField Tjabatan1;
    private javax.swing.JTextField Tjalan;
    private javax.swing.JTextField Tjalan1;
    private javax.swing.JTextField Tkecamatan;
    private javax.swing.JTextField Tkecamatan1;
    private javax.swing.JTextField Tkelurahan;
    private javax.swing.JTextField Tkelurahan1;
    private javax.swing.JTextField Tkodepos;
    private javax.swing.JTextField Tkodepos1;
    private javax.swing.JTextField Tnama;
    private javax.swing.JTextField Tnama1;
    private javax.swing.JTextField Tnik;
    private javax.swing.JTextField Tnik1;
    private javax.swing.JTextField Tno;
    private javax.swing.JTextField Tno1;
    private javax.swing.JTextField TnoHP;
    private javax.swing.JTextField TnoHP1;
    private javax.swing.JTextField Trt;
    private javax.swing.JTextField Trt1;
    private javax.swing.JTextField Trw;
    private javax.swing.JTextField Trw1;
    private javax.swing.JPanel Update;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnOK;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
