/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gym;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER RYZEN 5
 */
public class KelolaAlat extends javax.swing.JPanel implements database {
    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;

    /**
     * Creates new form KelolaPekerja
     */
    public KelolaAlat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        KelolaAlat = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        Add = new javax.swing.JPanel();
        AddTitle = new javax.swing.JLabel();
        LKodeAlat = new javax.swing.JLabel();
        LNamaAlat = new javax.swing.JLabel();
        LJenisAlat = new javax.swing.JLabel();
        TNamaAlat = new javax.swing.JTextField();
        TKodeAlat = new javax.swing.JTextField();
        TJenisAlat = new javax.swing.JTextField();
        SIMPAN = new javax.swing.JToggleButton();
        LLokasiAlat = new javax.swing.JLabel();
        TLokasiAlat = new javax.swing.JTextField();
        LKondisiAlat = new javax.swing.JLabel();
        TKondisiAlat = new javax.swing.JTextField();
        K1 = new javax.swing.JToggleButton();
        Read = new javax.swing.JPanel();
        TablePekerja = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        K2 = new javax.swing.JToggleButton();
        Edit = new javax.swing.JPanel();
        TableAlat1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        LNo = new javax.swing.JLabel();
        TNo = new javax.swing.JTextField();
        btnOK = new javax.swing.JToggleButton();
        K3 = new javax.swing.JToggleButton();
        Update = new javax.swing.JPanel();
        AddTitle1 = new javax.swing.JLabel();
        LKodeAlat1 = new javax.swing.JLabel();
        LNamaAlat1 = new javax.swing.JLabel();
        LJenisAlat1 = new javax.swing.JLabel();
        TNamaAlat1 = new javax.swing.JTextField();
        TKodeAlat1 = new javax.swing.JTextField();
        TJenisAlat1 = new javax.swing.JTextField();
        SIMPAN1 = new javax.swing.JToggleButton();
        LLokasiAlat1 = new javax.swing.JLabel();
        TLokasiAlat1 = new javax.swing.JTextField();
        LKondisiAlat1 = new javax.swing.JLabel();
        TKondisiAlat1 = new javax.swing.JTextField();
        K4 = new javax.swing.JToggleButton();
        Delete = new javax.swing.JPanel();
        TableAlat2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        LNo1 = new javax.swing.JLabel();
        TNo1 = new javax.swing.JTextField();
        btnOK1 = new javax.swing.JToggleButton();
        K5 = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(684, 316));
        setLayout(new java.awt.CardLayout());

        bodyPanel.setMaximumSize(new java.awt.Dimension(717, 316));
        bodyPanel.setMinimumSize(new java.awt.Dimension(717, 316));
        bodyPanel.setPreferredSize(new java.awt.Dimension(717, 316));

        mainPanel.setMaximumSize(new java.awt.Dimension(600, 400));
        mainPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        mainPanel.setLayout(new java.awt.CardLayout());

        KelolaAlat.setBackground(new java.awt.Color(204, 204, 204));
        KelolaAlat.setMinimumSize(new java.awt.Dimension(540, 370));

        Title.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Title.setText("KELOLA PERALATAN");

        btnTambah.setText("TAMBAH DATA PERALATAN");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE DATA");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRead.setText("LIHAT DATA PERALATAN");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE DATA");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KelolaAlatLayout = new javax.swing.GroupLayout(KelolaAlat);
        KelolaAlat.setLayout(KelolaAlatLayout);
        KelolaAlatLayout.setHorizontalGroup(
            KelolaAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KelolaAlatLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(KelolaAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KelolaAlatLayout.createSequentialGroup()
                        .addComponent(Title)
                        .addGap(98, 98, 98)))
                .addGap(110, 110, 110))
        );
        KelolaAlatLayout.setVerticalGroup(
            KelolaAlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelolaAlatLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Title)
                .addGap(35, 35, 35)
                .addComponent(btnTambah)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnRead)
                .addGap(11, 11, 11)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        mainPanel.add(KelolaAlat, "card7");

        Add.setBackground(new java.awt.Color(204, 204, 204));
        Add.setMinimumSize(new java.awt.Dimension(540, 370));

        AddTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        AddTitle.setText("Tambahkan Data Peralatan");

        LKodeAlat.setText("Kode Alat");

        LNamaAlat.setText("Nama Alat");

        LJenisAlat.setText("Jenis Alat");

        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        LLokasiAlat.setText("Lokasi Alat");

        LKondisiAlat.setText("Kondisi Alat");

        K1.setText("KEMBALI");
        K1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddLayout = new javax.swing.GroupLayout(Add);
        Add.setLayout(AddLayout);
        AddLayout.setHorizontalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addComponent(AddTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SIMPAN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(K1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddLayout.createSequentialGroup()
                            .addComponent(LJenisAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TJenisAlat))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddLayout.createSequentialGroup()
                            .addComponent(LKodeAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TKodeAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddLayout.createSequentialGroup()
                            .addComponent(LNamaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TNamaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addComponent(LKondisiAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TKondisiAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addComponent(LLokasiAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TLokasiAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(144, 144, 144))
        );
        AddLayout.setVerticalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddTitle)
                .addGap(45, 45, 45)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNamaAlat)
                    .addComponent(TNamaAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TKodeAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LKodeAlat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJenisAlat)
                    .addComponent(TJenisAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LLokasiAlat)
                    .addComponent(TLokasiAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TKondisiAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LKondisiAlat))
                .addGap(51, 51, 51)
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SIMPAN)
                    .addComponent(K1))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        mainPanel.add(Add, "card7");

        Read.setBackground(new java.awt.Color(204, 204, 204));
        Read.setMinimumSize(new java.awt.Dimension(540, 370));

        DefaultTableModel model = new DefaultTableModel();
        String[] columnNames={"No Alat", "Nama Alat", "Kode Alat", "Jenis Alat", "Lokasi Alat", "Kondisi Alat"};
        model.setColumnIdentifiers(columnNames);
        jTable1.setModel(model);
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            String sql = "SELECT * FROM Alat ORDER BY NoAlat ASC";
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("NoAlat"), rs.getString("NamaAlat"), rs.getString("KodeAlat"), rs.getString("JenisAlat"), rs.getString("LokasiAlat"), rs.getString("KondisiAlat")});
            }

            stmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Pengambilan Data Gagal", "", JOptionPane.ERROR_MESSAGE);
        }
        TablePekerja.setViewportView(jTable1);

        K2.setText("KEMBALI");
        K2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReadLayout = new javax.swing.GroupLayout(Read);
        Read.setLayout(ReadLayout);
        ReadLayout.setHorizontalGroup(
            ReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TablePekerja, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ReadLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(K2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReadLayout.setVerticalGroup(
            ReadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TablePekerja, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(K2)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        mainPanel.add(Read, "card7");

        Edit.setBackground(new java.awt.Color(204, 204, 204));
        Edit.setMinimumSize(new java.awt.Dimension(540, 370));

        DefaultTableModel model2 = new DefaultTableModel();
        String[] columnNames2={"No Alat", "Nama Alat", "Kode Alat", "Jenis Alat", "Lokasi Alat", "Kondisi Alat"};
        model2.setColumnIdentifiers(columnNames2);
        jTable2.setModel(model2);
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            String sql = "SELECT * FROM Alat ORDER BY NoAlat ASC";
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model2.addRow(new Object[]{rs.getString("NoAlat"), rs.getString("NamaAlat"), rs.getString("KodeAlat"), rs.getString("JenisAlat"), rs.getString("LokasiAlat"), rs.getString("KondisiAlat")});
            }

            stmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Pengambilan Data Gagal", "", JOptionPane.ERROR_MESSAGE);
        }
        TableAlat1.setViewportView(jTable2);

        LNo.setText("Masukkan Nomor yang Ingin  Diedit");

        TNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNoActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        K3.setText("KEMBALI");
        K3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditLayout = new javax.swing.GroupLayout(Edit);
        Edit.setLayout(EditLayout);
        EditLayout.setHorizontalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TableAlat1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(EditLayout.createSequentialGroup()
                        .addComponent(LNo)
                        .addGap(18, 18, 18)
                        .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EditLayout.createSequentialGroup()
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(K3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EditLayout.setVerticalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(TableAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNo)
                    .addComponent(TNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(K3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        mainPanel.add(Edit, "card7");

        Update.setBackground(new java.awt.Color(204, 204, 204));
        Update.setMinimumSize(new java.awt.Dimension(540, 370));

        AddTitle1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        AddTitle1.setText("Tambahkan Data Peralatan");

        LKodeAlat1.setText("Kode Alat");

        LNamaAlat1.setText("Nama Alat");

        LJenisAlat1.setText("Jenis Alat");

        SIMPAN1.setText("SIMPAN");
        SIMPAN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPAN1ActionPerformed(evt);
            }
        });

        LLokasiAlat1.setText("Lokasi Alat");

        LKondisiAlat1.setText("Kondisi Alat");

        K4.setText("KEMBALI");
        K4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateLayout = new javax.swing.GroupLayout(Update);
        Update.setLayout(UpdateLayout);
        UpdateLayout.setHorizontalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateLayout.createSequentialGroup()
                        .addComponent(AddTitle1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SIMPAN1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(K4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdateLayout.createSequentialGroup()
                            .addComponent(LJenisAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TJenisAlat1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdateLayout.createSequentialGroup()
                            .addComponent(LKodeAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TKodeAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdateLayout.createSequentialGroup()
                            .addComponent(LNamaAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TNamaAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UpdateLayout.createSequentialGroup()
                        .addComponent(LKondisiAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TKondisiAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateLayout.createSequentialGroup()
                        .addComponent(LLokasiAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TLokasiAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(144, 144, 144))
        );
        UpdateLayout.setVerticalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddTitle1)
                .addGap(45, 45, 45)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNamaAlat1)
                    .addComponent(TNamaAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TKodeAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LKodeAlat1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJenisAlat1)
                    .addComponent(TJenisAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LLokasiAlat1)
                    .addComponent(TLokasiAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TKondisiAlat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LKondisiAlat1))
                .addGap(51, 51, 51)
                .addGroup(UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SIMPAN1)
                    .addComponent(K4))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        mainPanel.add(Update, "card7");

        Delete.setBackground(new java.awt.Color(204, 204, 204));
        Delete.setMinimumSize(new java.awt.Dimension(540, 370));

        DefaultTableModel model3 = new DefaultTableModel();
        String[] columnNames3={"No Alat", "Nama Alat", "Kode Alat", "Jenis Alat", "Lokasi Alat", "Kondisi Alat"};
        model3.setColumnIdentifiers(columnNames3);
        jTable3.setModel(model3);
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            String sql = "SELECT * FROM Alat ORDER BY NoAlat ASC";
            rs = stmt.executeQuery(sql);

            while (rs.next()) {
                model3.addRow(new Object[]{rs.getString("NoAlat"), rs.getString("NamaAlat"), rs.getString("KodeAlat"), rs.getString("JenisAlat"), rs.getString("LokasiAlat"), rs.getString("KondisiAlat")});
            }

            stmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Pengambilan Data Gagal", "", JOptionPane.ERROR_MESSAGE);
        }
        TableAlat2.setViewportView(jTable3);

        LNo1.setText("Masukkan Nomor yang Ingin  Diedit");

        TNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNo1ActionPerformed(evt);
            }
        });

        btnOK1.setText("OK");
        btnOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOK1ActionPerformed(evt);
            }
        });

        K5.setText("KEMBALI");
        K5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteLayout = new javax.swing.GroupLayout(Delete);
        Delete.setLayout(DeleteLayout);
        DeleteLayout.setHorizontalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TableAlat2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(DeleteLayout.createSequentialGroup()
                        .addComponent(LNo1)
                        .addGap(18, 18, 18)
                        .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DeleteLayout.createSequentialGroup()
                                .addComponent(btnOK1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(K5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DeleteLayout.setVerticalGroup(
            DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DeleteLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(TableAlat2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNo1)
                    .addComponent(TNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK1)
                    .addComponent(K5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        mainPanel.add(Delete, "card7");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(648, 648, 648)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(bodyPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(Add);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(Edit);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(Read);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnReadActionPerformed

    private void TNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        Login admin = new Login();

        mainPanel.add(admin.getAdminPanel());
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnBackActionPerformed

    
    private void K1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K1ActionPerformed
        // TODO add your handling code here:
        kembali();
    }//GEN-LAST:event_K1ActionPerformed

    private void K2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K2ActionPerformed
        // TODO add your handling code here:
        kembali();
    }//GEN-LAST:event_K2ActionPerformed

    private void K3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K3ActionPerformed
        // TODO add your handling code here:
        kembali();
    }//GEN-LAST:event_K3ActionPerformed

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
        Add();
        kembali();
    }//GEN-LAST:event_SIMPANActionPerformed
    int pilih;
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        pilih = Integer.parseInt(TNo.getText());
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(Update);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnOKActionPerformed

    private void SIMPAN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPAN1ActionPerformed
        // TODO add your handling code here:
        Add(pilih);
        kembali();
    }//GEN-LAST:event_SIMPAN1ActionPerformed

    private void K4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_K4ActionPerformed

    private void TNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNo1ActionPerformed

    private void btnOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOK1ActionPerformed
        // TODO add your handling code here:
        pilih = Integer.parseInt(TNo1.getText());
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            
            String Alat = "DELETE FROM Alat WHERE NoAlat='"+pilih+"'";
            stmt.execute(Alat);
            
            JOptionPane.showMessageDialog(null, "Delete Data Berhasil", "", JOptionPane.INFORMATION_MESSAGE);

            stmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Delete Data Gagal", "", JOptionPane.ERROR_MESSAGE);
        }
        
        kembali();
    }//GEN-LAST:event_btnOK1ActionPerformed

    private void K5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K5ActionPerformed
        // TODO add your handling code here:
        kembali();
    }//GEN-LAST:event_K5ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(Delete);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnDeleteActionPerformed

    public JPanel getKelolaAlat(){
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(KelolaAlat);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        return mainPanel;
    }
    
    public void kembali()
    {
       mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
       
        mainPanel.add(KelolaAlat);
        mainPanel.repaint();
        mainPanel.revalidate(); 
    }
    
    public void Add(){
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            
            String Alat = "INSERT INTO Alat (NamaAlat, KodeAlat, JenisAlat, LokasiAlat, KondisiAlat) VALUES('"+TNamaAlat.getText()+"', '"+TKodeAlat.getText()+"', '"+TJenisAlat.getText()+"', '"+TLokasiAlat.getText()+"', '"+TKondisiAlat.getText()+"')";
            stmt.execute(Alat);
            
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil", "", JOptionPane.INFORMATION_MESSAGE);

            stmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Gagal", "", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void Add(int pilihan){
        try {
            Class.forName(JDBC_DRIVER);
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
            
            String Alat = "UPDATE Alat SET NamaAlat='"+TNamaAlat1.getText()+"', KodeAlat='"+TKodeAlat1.getText()+"', JenisAlat='"+TJenisAlat1.getText()+"', LokasiAlat='"+TLokasiAlat1.getText()+"', KondisiAlat='"+TKondisiAlat1.getText()+"' WHERE NoAlat='"+pilihan+"'";
            stmt.execute(Alat);
            
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil", "", JOptionPane.INFORMATION_MESSAGE);

            stmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Gagal", "", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add;
    private javax.swing.JLabel AddTitle;
    private javax.swing.JLabel AddTitle1;
    private javax.swing.JPanel Delete;
    private javax.swing.JPanel Edit;
    private javax.swing.JToggleButton K1;
    private javax.swing.JToggleButton K2;
    private javax.swing.JToggleButton K3;
    private javax.swing.JToggleButton K4;
    private javax.swing.JToggleButton K5;
    private javax.swing.JPanel KelolaAlat;
    private javax.swing.JLabel LJenisAlat;
    private javax.swing.JLabel LJenisAlat1;
    private javax.swing.JLabel LKodeAlat;
    private javax.swing.JLabel LKodeAlat1;
    private javax.swing.JLabel LKondisiAlat;
    private javax.swing.JLabel LKondisiAlat1;
    private javax.swing.JLabel LLokasiAlat;
    private javax.swing.JLabel LLokasiAlat1;
    private javax.swing.JLabel LNamaAlat;
    private javax.swing.JLabel LNamaAlat1;
    private javax.swing.JLabel LNo;
    private javax.swing.JLabel LNo1;
    private javax.swing.JPanel Read;
    private javax.swing.JToggleButton SIMPAN;
    private javax.swing.JToggleButton SIMPAN1;
    private javax.swing.JTextField TJenisAlat;
    private javax.swing.JTextField TJenisAlat1;
    private javax.swing.JTextField TKodeAlat;
    private javax.swing.JTextField TKodeAlat1;
    private javax.swing.JTextField TKondisiAlat;
    private javax.swing.JTextField TKondisiAlat1;
    private javax.swing.JTextField TLokasiAlat;
    private javax.swing.JTextField TLokasiAlat1;
    private javax.swing.JTextField TNamaAlat;
    private javax.swing.JTextField TNamaAlat1;
    private javax.swing.JTextField TNo;
    private javax.swing.JTextField TNo1;
    private javax.swing.JScrollPane TableAlat1;
    private javax.swing.JScrollPane TableAlat2;
    private javax.swing.JScrollPane TablePekerja;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel Update;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JToggleButton btnOK;
    private javax.swing.JToggleButton btnOK1;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
